version: '3.8'

services:
  db_prod:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  frontend_prod:
    build:
      context: ./frontend
      args:
        - API_URL=${API_URL:-http://localhost:8080}
    ports:
      - 3000:3000
    env_file:
      - ./.env.front

  backend_prod:
    build: ./backend
    command: /go/main 
    volumes:
      - ./backend:/usr/src/app
      - upload_data_dev:/var/uploads
    ports:
      - 8080:8080
    env_file:
      - ./.env.back
    depends_on:
      - frontend_prod
      - db_prod

volumes:
  postgres_data:
  upload_data_dev:
