version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    env_file:
      - ./.env.db

  frontend:
    container_name: react
    build: ./frontend
    ports:
      - '2137:2137'
    env_file:
      - ./.env.front

  backend:
    container_name: go
    build: ./backend
    command: /go/main
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 8080:8080
    env_file:
      - ./.env.back
    depends_on:
      - frontend
      - db

volumes:
  postgres_data:
