version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/gopoker/src

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./backend:/usr/src/gopoker
    ports:
      - 8080:8080
    env_file:
      - ./.env.back.dev
    depends_on:
      - db
      - frontend

volumes:
  postgres_data_dev:
