services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  db-test:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.db.test

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/gopoker/src

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./backend:/usr/src/gopoker
      - upload_data_dev:/var/uploads
    ports:
      - 8080:8080
    env_file:
      - ./.env.back.dev
    depends_on:
      - db
      - frontend

volumes:
  postgres_data_dev:
  upload_data_dev:
